### PR TITLE
added a bot to find pokemon and level up in a specified channel

### PR DESCRIPTION
**Pull request by schan3Ed**
A bot will print a message in a specified discord channel in a specified delay time frame.
This will help level up the pokemon and help spawn new pokemon.

### CODE REVIEW

**Comment by Hyperclaw79** [comment]
Have you tested it out if it works everytime?
Moreover you're allowing the users to set the delay. So if someone sets a very low delay, it would be ineffective. 
Another possible drawback I see is, that if you are using this selfbot in a public server with carefully customized catch delays to make the bot look as genuine as possible, repeatedly sending that "Finding a pokemon..." message might blow the cover.

**Comment by xKynn** [comment]
Personally I'm not too keen on spamming.
Code wise, delay isn't the best option because of discord rate limits, it should have a lower limit, secondly, from what i know pokecord does check for spam, and it might be a levenshtein check. randomized text will work better

**Comment by schan3Ed** [comment]
The idea of the delay time is to minimize the annoyance of spam, and that's based on the server that user is in. Users should have the choice to decide how long it takes between each message.
i.e. private server public channel, more time, like 10 seconds
i.e. private server private channel, less time, like half a second

I do not intend to mimic human.

I like the idea of using user specified random phases. Will implement that.

In terms of testing. It works on two of my friend's laptop. The code is rather simple so it should work as long as discord.py doesn't break.

**Comment by Hyperclaw79** [comment]
Hmm, I share Demo's POV on this one. I don't think it's a good idea to make an autospammer available to the public masses given how much the Pokecord bot lags already.
Moreover, if people really need a spammer, they could use the one in my [Premium Version](https://github.com/Hyperclaw79/PokeBall-SelfBot#donations) which is already battle-tested and efficient.
Well, either way, it's Demo's call. For now, update the message being sent to bypass levenshtein check.

**Comment by schan3Ed** [comment]
Oh, I was not aware there is a premium version haha. My bad.

I think the pokemon catching function can also be misused by the users. 
But anyway, I have seen people spamming "." or "asd" in chat to finding pokemon and thought this could help them and that is my intention to add this feature.

No worries if you guys do not wish to merge this in haha. I just thought this could be a cute little feature add-on to the pokemon catcher

**Pull request closed without merging**
